//
// iac/prd/nosql/variables.tf
//

variable "compartment_ocid" {}

//
// Table: fotogal_ntable_images
//
variable "fotogal_ntable_images_ddl" {
    default = <<EOS
       CREATE TABLE IF NOT EXISTS fotogal_ntable_images (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
          image_url STRING,
          image_filename STRING,
          image_original_filename STRING,
          image_host_fqdn STRING,
          image_uri  STRING,
          image_type ENUM (png, jpeg, gif),
          user_id INTEGER,
          created_ts INTEGER,
          liked_list ARRAY(INTEGER),
          disliked_list ARRAY(INTEGER),
          main_comment STRING,
          is_profile BOOLEAN,
       PRIMARY KEY(id))
   EOS
}

//
// Table: fotogal_ntable_users
//
variable "fotogal_ntable_users_ddl" {
    default = <<EOS
       CREATE TABLE IF NOT EXISTS fotogal_ntable_users (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
          email STRING,
          full_name STRING,
          username STRING,
          password STRING,
          follow_list ARRAY(INTEGER),
          follow_sent_list ARRAY(INTEGER),
          follow_you_list ARRAY(INTEGER),
          follow_received_list ARRAY(INTEGER),
          created_ts INTEGER,
          is_private BOOLEAN,
          is_professional_account BOOLEAN,
          profile_image_url STRING,
          user_data JSON,
       PRIMARY KEY(id, email, username))
    EOS
}

//
// Table: fotogal_ntable_authsession
//
variable "fotogal_ntable_authsession_ddl" {
    default = <<EOS
       CREATE TABLE IF NOT EXISTS fotogal_ntable_authsession (
          random_token STRING,
          created_ts INTEGER,
          expire_ts INTEGER,
          user_id INTEGER,
       PRIMARY KEY(random_token))
    EOS
}